# Generated by Django 5.2.5 on 2025-08-29 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('snmp_community', models.CharField(default='public', max_length=50)),
                ('system_description_oid', models.CharField(default='1.3.6.1.2.1.1.1.0', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_reachable', models.BooleanField()),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='switch.switch')),
            ],
        ),
    ]
