# Generated by Django 5.2.5 on 2025-08-29 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pinghistory',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='switch',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Son Görülme'),
        ),
        migrations.AddField(
            model_name='switch',
            name='status',
            field=models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('unknown', 'Unknown')], default='unknown', max_length=10, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='pinghistory',
            name='response_time',
            field=models.FloatField(blank=True, help_text='ms cinsinden', null=True),
        ),
        migrations.AlterField(
            model_name='pinghistory',
            name='switch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ping_history', to='switch.switch'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='brand',
            field=models.CharField(max_length=50, verbose_name='Marka'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='ip_address',
            field=models.GenericIPAddressField(unique=True, verbose_name='IP Adresi'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='model',
            field=models.CharField(max_length=50, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Cihaz Adı'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='snmp_community',
            field=models.CharField(default='public', max_length=50, verbose_name='SNMP Community'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='system_description_oid',
            field=models.CharField(default='1.3.6.1.2.1.1.1.0', max_length=200, verbose_name='Sistem Açıklaması OID'),
        ),
    ]
