# Generated by Django 5.2.5 on 2025-09-01 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0002_alter_pinghistory_options_switch_last_seen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='switch',
            name='brand',
        ),
        migrations.AddField(
            model_name='switch',
            name='snmp_version',
            field=models.CharField(choices=[('1', 'SNMP v1'), ('2c', 'SNMP v2c'), ('3', 'SNMP v3')], default='2c', max_length=5),
        ),
        migrations.AlterField(
            model_name='switch',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='switch.devicemodel', verbose_name='Model'),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='switch.vendor'),
        ),
        migrations.AddField(
            model_name='switch',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='switch.vendor', verbose_name='Marka'),
            preserve_default=False,
        ),
    ]
