# Generated by Django 5.2.6 on 2025-09-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0003_devicemodel_vendor_remove_switch_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='device_type',
            field=models.CharField(default='cisco_ios', help_text='Örn: cisco_ios, hp_procurve, arista_eos', max_length=50, verbose_name='Cihaz Tipi (Netmiko için)'),
        ),
        migrations.AddField(
            model_name='switch',
            name='password',
            field=models.CharField(blank=True, max_length=100, verbose_name='SSH Şifresi'),
        ),
        migrations.AddField(
            model_name='switch',
            name='username',
            field=models.CharField(blank=True, max_length=100, verbose_name='SSH Kullanıcı Adı'),
        ),
    ]
